name: Tests

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@a502f66dedae6774c819ff3c80406c7e8266dad2

      - name: Run tests
        run: timeout 20m cargo test
